apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::533267218830:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-B1oMlyC0NxAf
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::533267218830:user/harish
      username: harish
kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-05T01:35:42Z"
  name: aws-auth
  namespace: kube-system
  uid: f590182d-d73d-48de-b741-cd37c1dcbe54 #don't delete this